# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f1c00d774a1326ee8ce6c6a25817b27c173116e4edc1529e645f2a423f90907488fc1715329b88b76cce9859b1410069ee2d96550609cfde65d4422b256b145

test:
  secret_key_base: 69d1baf0d630ac07eb5b0e71685974b98587ac7b3e4a9be94bcbe5a3120320a5a0752bdc07028edcc41feb1cfac50cdd811fd5a11fbe41de6ff171cf21d16fa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
